pub mod actor;
pub mod animation;
pub mod armor;
pub mod class;
pub mod enemy;
pub mod item;
pub mod map;
pub mod skill;
pub mod state;
pub mod system;
pub mod tileset;
pub mod troop;
pub mod weapon;

pub use actor::Actor;
pub use animation::Animation;
pub use armor::Armor;
pub use class::Class;
pub use enemy::Enemy;
pub use item::Item;
pub use map::Map;
pub use skill::Skill;
pub use state::State;
pub use system::System;
pub use tileset::Tileset;
pub use troop::Troop;
pub use weapon::Weapon;

use crate::structured::NilPadded;

pub type Actors = NilPadded<Actor>;
pub type Animations = NilPadded<Animation>;
pub type Armors = NilPadded<Armor>;
pub type Classes = NilPadded<Class>;
pub type Enemies = NilPadded<Enemy>;
pub type Items = NilPadded<Item>;
pub type Skills = NilPadded<Skill>;
pub type States = NilPadded<State>;
pub type Tilesets = NilPadded<Tileset>;
pub type Troops = NilPadded<Troop>;
pub type Weapons = NilPadded<Weapon>;
